### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by FGRemastered** [FGRemastered/VariantsDecisionZMM#1]
### Small Arms
- [x] Infantry Equipment
- [x] Artillery
- [x] Rocket Artillery
- [x] Anti-Air
- [x] Anti-Tank

### Tanks
- [x] Lights
- [x] Mediums
- [x] Heavys
- [x] Speicals
- [x] Untracked
- [ ] The New Order (works, but could be prettier)
- [ ] Novum Vexillum
- [ ] Millenium Dawn

### Planes
- [x] Lights
- [x] Mediums
- [x] Heavys
- [x] Rockets
- [ ] The New Order
- [ ] Novum Vexillum (works, but could be prettier)
- [ ] Millenium Dawn

### Navy
- [x] CV
- [x] BB
- [x] BC
- [x] CA
- [x] CL
- [x] DD
- [x] SS
- [x] Dreadnought
- [x] Panzerschiff
- [x] Coastal Defense Ship
- [x] Torpedo Cruiser
- [x] Cruiser Sub
- [ ] The New Order
- [x] Novum Vexillum
- [ ] Millenium Dawn

### Misc
- [x] Fix bug created by changing the names for the Navy decisions in the debug menu
- [x] ~~Switch the Ship spawning from `scripted_effects` to `oob`~~ Add oob for the base-fleet
- [x] Add a check for "Death or Dishonour" for the equipment licensing
